### ISSUE TITLE
Loading DLL

### ISSUE THREAD

**Issue by STRATZ-Ken** [Shane32/graphql-dotnet#3]
Hello @Shane32 ,

Thanks for your help.

I do not just use GraphQL Core. I use Transports and WebSockets as well. Actually, it seems no matter what I do, I cannot see `IDataLoaderResult` in the DLL i compile.  I know its there, as I see it in your source code, but when I compile the dll, move to my project, add the reference, then open the dll, I dont see it in Object Browser.  

Any ideas?

**Comment by STRATZ-Ken** [comment]
As a helpful guide, I think the system is overriding the path I give it in the Assemblies.

For example, if I manually override C:\Users\XXXX\.nuget\packages\graphql\3.0.0-preview-1490\lib\netstandard2.0 to your DLL, now I can see the IDataLoaderResult in the Object Browsers.  But that wont work when I try to send my project off to TeamCity build servers.

**Comment by STRATZ-Ken** [comment]
Got this working.

I basically removed everything on GraphQL that was a dependency, locally build each dll for each project.  Then referenced them locally into their own DLLs. And bam, and your code works flawlessly.  Great work @Shane32

**Comment by Shane32** [comment]
Sorry I never got a chance to answer this morning.  You've basically hit the nail on the head; nuget dependencies conflict with local dll references.  I've never figured out how to override a specific nuget package with a local dll.  If you figure it out, let me know.  Until then, you'll probably need to manually build and include all those packages.
